apiVersion: apps/v1
kind: Deployment
metadata:
  name: aml
  labels:
    app: aml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aml
  template:
    metadata:
      labels:
        app: aml
    spec:
      containers:
        - name: aml
          image:  houssemhosni/acm-web:aml-service
          ports:
            - containerPort: 8098
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "consul-consul-server.consul.svc.cluster.local"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "8500"
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: my-registry-secret
