apiVersion: v1
kind: Service
metadata:
  name: credit-service
  labels:
    app: credit
  namespace: default
spec:
  type: NodePort
  selector:
    app: credit
  ports:
    - protocol: TCP
      port: 8081        # Port accessible à l'intérieur du cluster
      targetPort: 8081  # Port exposé par le conteneur
      nodePort: 30081   # Port accessible depuis l'extérieur (doit être entre 30000-32767)
