apiVersion: v1
kind: Service
metadata:
  name: crm-service
  labels:
    app: crm
spec:
  type: NodePort
  selector:
    app: crm
  ports:
    - port: 8094           # Port exposé par le service
      targetPort: 8094     # Port dans le conteneur
      nodePort: 30094      # Port sur le nœud (doit être entre 30000-32767)
