apiVersion: apps/v1
kind: Deployment
metadata:
  name: parametrage
  labels:
    app: parametrage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parametrage
  template:
    metadata:
      labels:
        app: parametrage
    spec:
      containers:
      - name: parametrage
        image: houssemhosni/acm-web-parametrage-service:v2
        ports:
        - containerPort: 8091  # Mis à jour pour correspondre au port Spring Boot
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_CLOUD_CONSUL_HOST
          value: "consul-consul-server.consul.svc.cluster.local"
        - name: SPRING_CLOUD_CONSUL_PORT
          value: "8500"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      imagePullSecrets:
      - name: my-registry-secret
